homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name="index"),
    path('journal/', views.comingsoon, name="comingsoon")
]

jadwal/urls.py
from django.urls import path
from . import views

app_name = 'jadwal'

urlpatterns = [
    path('', views.index, name="index"),
    path('terima/', views.terima, name="terima"),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jadwal/', include('jadwal.urls'))
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models

class JadwalModel(models.Model):
    namaKegiatan = models.CharField('Nama Kegiatan', max_length=200, help_text="Nama kegiatan yang dilakukan")
    tempatKegiatan = models.CharField('Tempat Kegiatan', max_length=100, help_text="Tempat kegiatan dilakukan")
    waktuKegiatan = models.DateTimeField('Waktu Kegiatan')
    kategoriKegiatan = models.CharField('Kategori Kegiatan', max_length=10)

    def __str__(self):
        return self.namaKegiatan

jadwal/forms.py
from django import forms

# Create your models here.
class JadwalKegiatan(forms.Form):
    # Nama kegiatan
    namaKegiatan = forms.CharField(label='Nama Kegiatan' ,max_length=200, initial="Nama kegiatan")

    # Tempat kegiatan
    tempatKegiatan = forms.CharField(label='Tempat kegiatan', max_length=100, initial="Tempat kegaitan")

    # Waktu kegiatan (tanggal, jam)
    # nanti kalo udah bener hari bisa diambil pake datetime python
    waktuKegiatan = forms.DateTimeField(
        label='Waktu kegiatan',

        # Ganti widget default ke widget Bootstrap
        widget = forms.DateTimeInput(attrs = {
            'class': 'form-control datetimepicker-input',
            'data-target': '#datetimepicker1',
        }),

        initial='Waktu kegiatan'
    )

    # Kategori kegiatan
    KATEGORI = [('Safe', 'Safe'), ('Urgent', 'Urgent'), ('Important', 'Important')]
    kategoriKegiatan = forms.ChoiceField(choices=KATEGORI)

homepage/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

def comingsoon(request):
    return render(request, 'comingsoon.html')

jadwal/views.py
from django.shortcuts import render
from .forms import JadwalKegiatan
from .models import JadwalModel

# Create your views here.
def index(request):
    jadwal = JadwalKegiatan()
    semuaKegiatan = JadwalModel.objects.all()
    
    argument = {
        'formJadwal' : jadwal,
        'semuaKegiatan' : semuaKegiatan,
    }

    return render(request, 'jadwal/index.html', argument)

def terima(request):
    jadwal = JadwalKegiatan()
    isianNamaKegiatan = request.POST['namaKegiatan']
    isianTempatKegiatan = request.POST['tempatKegiatan']
    isianWaktuKegiatan = request.POST['waktuKegiatan']
    isianKategoriKegiatan = request.POST['kategoriKegiatan']

    temp = JadwalModel(
        namaKegiatan = isianNamaKegiatan, 
        tempatKegiatan = isianTempatKegiatan, 
        waktuKegiatan = isianWaktuKegiatan,
        kategoriKegiatan = isianKategoriKegiatan,
    )

    temp.save()

    semuaKegiatan = JadwalModel.objects.all()
    
    argument = {
        'formJadwal' : jadwal,
        'semuaKegiatan' : semuaKegiatan,
    }

    return render(request, 'jadwal/index.html', argument)

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    
    {% block customHead %}
    {% endblock customHead %}

    <title>Portofolio - Doan Andreas Nathanael</title>
</head>
<body>
    <!-- Navbar -->
    <nav id="mainNavbar" class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
        <!-- Container isi navbar -->
        <div class="container">
            <!-- Brand navbar -->
            <a class="navbar-brand" href="{% url 'homepage:index' %}">&&&</a>
            
            <!-- Toggler button -->
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navLinks" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <!-- Isi navbar -->
            <div class="collapse navbar-collapse" id="navLinks">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item"><a class="nav-link" href="#about">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#experience">Experiences</a></li>
                    <li class="nav-item"><a class="nav-link" href="#skills">Skills</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'homepage:comingsoon' %}">Journey</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'homepage:comingsoon' %}">Blog</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'jadwal:index' %}">Jadwal</a></li>
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    
    <!-- Contacts -->
    <footer id="contacts" class="row align-items-center bg-dark contacts-section container-fluid">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <p class="text-light display-4 visiting">Thanks for<br>visiting!</p>
                </div>
                <div class="align-self-center text-light h2">
                    <h5 class="mb-3">Get in touch:</h5>
                    <a href="#"><img src="{% static 'img/gmail-icon.svg' %}" alt="gmail" class="mr-4"></a>
                    <a href="#"><img src="{% static 'img/line-icon.svg' %}" alt="gmail" class="mr-4"></a>
                    <a href="#"><img src="{% static 'img/instagram-icon.svg' %}" alt="gmail" class="mr-4"></a>
                    <a href="#"><img src="{% static 'img/gitlab-icon.svg' %}" alt="gmail" class="mr-4"></a>
                    <a href="https://www.linkedin.com/in/doan-butarbutar-7b5680177/"><img src="{% static 'img/linkedin-icon.svg' %}" alt="gmail"></a>
                </div>
            </div>
        </div>
    </footer>

    
</body>
</html>

homepage/templates/comingsoon.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<!-- Landing Page / Header -->
<header class="container-fluid jumbotron">
    <div class="row align-items-center text-center">

        <!-- Image -->
        <div class="col-md-5 order-2 order-md-1">
            <div class="row justify-content-end">
                <div class="col-9">
                    <img class="img-fluid" src="{% static 'img/pluto-coming-soon-1.png' %}" alt="Coming soon illustration">
                </div>
            </div>
        </div>

        <!-- Content -->
        <div class="col order-1 order-md-2">
            <div class="row justify-content-center">
                <div id="headingGroup" class="col-10 h2 text-left">
                    <span class="h5">
                        Curious, eh?<br>
                        This section is<br>
                    </span> 
                    <span class="name display-2">Coming Soon.</span><br>
                    <span class="h5">
                        Come back later for more<br>
                        about me. Oh, and i can also<br>
                        notify you when it's finally up.<br>
                    </span>
                    <a href="#" class="btn btn-danger mt-4">Notify me!</a>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock content %}

homepage/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <!-- Landing Page / Header -->
    <header class="container-fluid jumbotron">
        <div class="row align-items-center text-center">

            <!-- Image -->
            <div class="col-md-5 order-1">
                <div class="row justify-content-end">
                    <div class="col-md-9">
                        <img class="img-fluid" src="{% static 'img/myphoto2.png' %}" alt="My photo">
                    </div>
                </div>
            </div>

            <!-- Content -->
            <div class="col-md-7 order-2">
                <div class="row justify-content-center">
                    <div id="headingGroup" class="col-md-10 text-md-left">
                        <span class="h5">My name is</span> <br>
                        <span class="name display-2">Doan Andreas Nathanael</span> <br>
                        <span class="h3 isi">Designer, Web Developer, Data Scientist.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <main class="container-fluid">
        <!-- About -->
        <section id="about" class="row align-items-center about-section p-5">
            <div class="container">
                <div class="row justify-content-between section-container">
                    <!-- About #1 -->
                    <div class="col-sm-10 col-lg-7 align-self-start section-style mb-3 mb-md-5">
                        <h2>About</h2>
                        <p class="h2">
                            I’m a conceptual thinker that strive to learn the deep roots and “Why’s” of the things that pique my curiosity. 
                            I love to create good designs that deliver impact to the audience.
                        </p>
                    </div>
            
                    <!-- About #2 -->
                    <div class="col-sm-10 col-lg-5 align-self-end">
                        <p>
                            My mom was a middle school teacher. Thanks to her, i develop a liking towards academics and teaching. 
                            I always like to tutor my friends in high school when i could, and when i do, i always try to paraphrase my words 
                            and actions carefully so that my friends would get the grasp of the subjects easily. Now as a designer, i am learning 
                            to bridge my intuition to paraphrase words, to paraphrasing visual cues so that people understand better.
                        </p>
                    </div>
                </div>
            </div>
        </section>

        <!-- Experience -->
        <section id="experience" class="row align-items-center experience-section">
            <div class="container section-style section-container p-5">
                <h2>Experiences</h2>
                <div class="row section-style ">
                    <!-- Kartu 1 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Ristek Fasilkom UI 2020</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Junior Member DPD</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>

                    <!-- Kartu 2 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Pekan Ristek 2019</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Creative Division Lead</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>

                    <!-- Kartu 3 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">BEM Fasilkom UI</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Staff of Media</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>

                    <!-- Kartu 4 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Fourth Thing</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>
                        
                    <!-- Kartu 5 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Fifth Thing</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>
                
                    <!-- Kartu 6 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Sixth Thing</h5>
                                <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6>
                                <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda corrupti quam magnam! Veniam, dolorum facere? Commodi, ut. Et, itaque quam!</p>
                                <a href="#experience" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>
                
                </div>
            </div>
        </section>

        <!-- Skills -->
        <section id="skills" class="row align-items-center skills-section p-5">
            <div class="container section-style section-container">
                <h2>Skills</h2>
                <div class="row section-style card-group">
                    <!-- Kartu 1 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Developer Skills</h5>
                                <p class="card-text">
                                    Python 3<br>
                                    Java<br>
                                    <br>
                                    HTML5<br>
                                    CSS3<br>
                                    JavaScript<br>
                                    Django<br>
                                    <br>
                                    Github<br>
                                    Gitlab<br>
                                    <br>
                                    MIPS                                        
                                </p>
                                <a href="#skills" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>

                    <!-- Kartu 2 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Designing Skills</h5>
                                <p class="card-text">
                                    “Universal Principles of Designs” Knowledge<br>
                                    <br>
                                    Graphic Design<br>
                                    <br>
                                    UI/UX Design<br>
                                    <br>
                                    Web Design<br>
                                    <br>
                                    Information Architecture                                      
                                    </p>
                                <a href="#skills" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>

                    <!-- Kartu 3 -->
                    <div class="col-md-6 col-lg-4 mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">Misc. Skills</h5>
                                <p class="card-text">
                                    Intrapersonal Skills<br>
                                    <br>
                                    Research Proficiency<br>
                                    <br>
                                    Working Under Pressure<br>
                                    <br>
                                    Organization Skills<br>
                                    <br>
                                    Progressive Thinking<br>
                                    <br>
                                    Open Minded                                        
                                </p>
                                <a href="#skills" class="btn btn-outline-success btn-sm">Read more</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>

{% endblock %}

jadwal/templates/jadwal/hasil.html
<html>
    hasil
    <br>
    {{ dataNamaKegiatan }}
    <br>
    {{ dataTempatKegiatan }}
    <br>
    {{ dataWaktuKegiatan }}
    <table>
        {% for objek in semuaPesan %}
            <tr>
                <td>
                    {{ objek.modelNamaKegiatan }}
                    {{ objek.modelTempatKegiatan }}
                    {{ objek.modelWaktuKegiatan }}
                </td>
            </tr>
        {% endfor %}
    </table>
</html>

jadwal/templates/jadwal/index.html
{% extends "base.html" %}
{% block customHead %}
    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>
{% endblock customHead %}

{% block content %}
<!-- Landing Page / Header -->
<header class="container-fluid jumbotron">
    <div class="row align-items-center text-center">

        <!-- Isian Form -->
        <div class="col-8 order-1">
            <div class="row justify-content-center">
                <form method="POST" action="/jadwal/terima/">
                    {% csrf_token %} <br>
                    {{ formJadwal.namaKegiatan }} <br>
                    {{ formJadwal.tempatKegiatan }} <br>
                    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
                        {{ formJadwal.waktuKegiatan }}
                        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
                            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
                        </div>
                    </div>
                    {{ formJadwal.kategoriKegiatan }}
                    <input type="submit" value="Buat Jadwal" name="tombol">
                </form>     
            </div>
        </div>

        <!-- Konten Jadwal -->
        <div class="col-4 order-2">
            <div class="row justify-content-center">
                <div id="headingGroup" class="col-md-10 text-md-left">

                    {% for kegiatan in semuaKegiatan %}
                    <!-- Kartu Kegiatan -->
                    <div class="col mb-4">
                        <div class="card">
                            <div class="card-body">
                                <h5 class="card-title">{{ kegiatan.namaKegiatan }}</h5>
                                <h6 class="card-subtitle mb-2">{{ kegiatan.tempatKegiatan }}</h6>
                                <p class="card-subtitle mb-2 text-muted">{{ kegiatan.waktuKegiatan }}</p>
                                <h6 class="card-subtitle mb-2">{{ kegiatan.kategoriKegiatan }}</h6>
                                <a href="#" class="btn btn-outline-danger btn-sm">Hapus Kegiatan</a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </div>
        </div>

    </div>
</header>

<script>
$(function () {
    $("#datetimepicker1").datetimepicker({
    format: 'YYYY-MM-DD HH:mm:ss',
    });
});
</script>
{% endblock content %}

jadwal/templates/jadwal/jadwal.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Static Example</title>

    <!-- Bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    <!-- Font Awesome -->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <!-- Moment.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.23.0/moment.min.js" integrity="sha256-VBLiveTKyUZMEzJd6z2mhfxIqz3ZATCuVMawPZGzIfA=" crossorigin="anonymous"></script>

    <!-- Tempus Dominus Bootstrap 4 -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/css/tempusdominus-bootstrap-4.min.css" integrity="sha256-XPTBwC3SBoWHSmKasAk01c08M6sIA5gF5+sRxqak2Qs=" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.1.2/js/tempusdominus-bootstrap-4.min.js" integrity="sha256-z0oKYg6xiLq3yJGsp/LsY9XykbweQlHl42jHv2XTBz4=" crossorigin="anonymous"></script>

  </head>
  <body>

    <div class="input-group date" id="datetimepicker1" data-target-input="nearest">
        <input type="text" class="form-control datetimepicker-input" data-target="#datetimepicker1"/>
        <div class="input-group-append" data-target="#datetimepicker1" data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
        </div>
    </div>

    <script>
      $(function () {
        $("#datetimepicker1").datetimepicker();
      });
    </script>

  </body>
</html>